import { cloneDefaults, simulate } from './model.js';
import { renderCharts } from './charts.js';
let state = cloneDefaults(), result, pinned = null, activePreset = 'balanced';
const $ = id => document.getElementById(id), fmt = n => Math.round(n).toLocaleString(), pct = n => `${(n * 100).toFixed(1)}%`;
const policyNames = {priority:'Priority allocation', fair:'Fair-share allocation', margin:'Margin-maximizing allocation', hybrid:'Hybrid allocation'};
const policyDescriptions = {priority:'Allocates constrained supply to the highest service tier first, then works down through the segment hierarchy.', fair:'Shares available supply proportionally across all segment needs to balance service levels.', margin:'Prioritizes the segments that capture the most margin for every unit available.', hybrid:'Reserves a portion of supply for the top tier, then distributes the remaining supply fairly.'};
function set(id, value, suffix = '') { $(id).value = value; $(`${id}Out`).value = `${value}${suffix}`; }
function controls() {
  set('weeks', state.weeks); set('inventory', state.startingInventory); set('safety', state.safetyStock); set('demand', state.demandMultiplier || 100, '%'); set('reserve', state.reservePct, '%');
  $('seed').value = state.seed; $('policy').value = state.policy;
  $('plants').innerHTML = state.plants.map((p,i) => `<div class="mini"><b>${p.name}</b><label>Weekly capacity <output>${fmt(p.capacity)}</output><input data-path="plants.${i}.capacity" type="range" min="0" max="1500" step="10" value="${p.capacity}"></label><label>Yield <output>${p.yield}%</output><input data-path="plants.${i}.yield" type="range" min="50" max="100" value="${p.yield}"></label><label>Lead time <output>${p.leadTime} wk</output><input data-path="plants.${i}.leadTime" type="range" min="0" max="12" value="${p.leadTime}"></label></div>`).join('');
  $('segments').innerHTML = state.segments.map((s,i) => `<div class="mini"><b>${s.name}</b><small>Tier ${s.tier} · $${s.margin}/unit · ${s.backorder ? 'backorder' : 'lost sales'}</small><label>Baseline demand <output>${fmt(s.baseline)}</output><input data-path="segments.${i}.baseline" type="range" min="20" max="800" step="10" value="${s.baseline}"></label><label>Growth <output>${s.growth}%</output><input data-path="segments.${i}.growth" type="range" min="-2" max="5" step=".1" value="${s.growth}"></label></div>`).join('');
  document.querySelectorAll('[data-preset]').forEach(b => b.classList.toggle('selected', b.dataset.preset === activePreset));
}
function spark(values, color) { const max = Math.max(...values, 1), min = Math.min(...values, 0), range = max - min || 1; const points = values.map((v,i) => `${i/(values.length-1||1)*100},${15-(v-min)/range*13}`).join(' '); return `<svg class="spark" viewBox="0 0 100 15" preserveAspectRatio="none"><polyline fill="none" stroke="${color}" stroke-width="1.5" points="${points}"/></svg>`; }
function renderKpis() { const s = result.summary, p = pinned, gap = s.margin - s.unconstrainedMargin;
  const cards = [
    ['Fill Rate', pct(s.fillRate), 'fillRate', result.weeks.map(w => w.demand.reduce((a,b)=>a+b,0) ? w.shipments.reduce((a,b)=>a+b,0)/w.demand.reduce((a,b)=>a+b,0) : 1)],
    ['Units Shipped', fmt(s.shipped), 'shipped', result.weeks.map(w => w.shipments.reduce((a,b)=>a+b,0))],
    ['Lost Sales', fmt(s.lost), 'lost', result.weeks.map(w => w.lost.reduce((a,b)=>a+b,0))],
    ['Backlog', fmt(s.backlog), 'backlog', result.weeks.map(w => w.backlog.reduce((a,b)=>a+b,0))],
    ['Margin Captured', `$${fmt(s.margin)}`, 'margin', result.weeks.map(w => w.shipments.reduce((a,x,i)=>a+x*state.segments[i].margin,0)), `${pct(s.unconstrainedMargin ? s.margin/s.unconstrainedMargin : 1)} · $${fmt(Math.abs(gap))} gap`],
    ['Ending Inventory', fmt(s.inventory), 'inventory', result.weeks.map(w => w.inventory)],
    ['Constrained Weeks', `${s.constrainedWeeks}/${state.weeks}`, 'constrainedWeeks', result.weeks.map(w => w.constrained ? 1 : 0)],
    ['Avg Capacity Util.', pct(s.utilization), 'utilization', result.weeks.map(w => w.utilization)]
  ];
  $('kpis').innerHTML = cards.map(([name,value,key,series,note]) => { const delta = p && p[key] != null ? s[key] - p[key] : null; const positive = key === 'lost' || key === 'backlog' || key === 'constrainedWeeks' ? delta <= 0 : delta >= 0; const label = delta == null ? (note || 'Active scenario') : `<span class="delta ${positive?'up':'down'}">${positive?'↑':'↓'} ${key.includes('Rate') || key === 'utilization' ? pct(Math.abs(delta)) : fmt(Math.abs(delta))} vs A</span>`; return `<div class="kpi"><span>${name}</span><strong>${value}</strong><em>${label}</em>${spark(series, positive ? '#3B8F81' : '#F4562C')}</div>`; }).join('');
  $('compare').hidden = !p; if (p) $('compare').textContent = 'Comparing the active scenario with pinned Scenario A. KPI deltas and trends reflect the current run.';
}
function weekLabel(i) { const start = 40, week = ((start - 1 + i) % 52) + 1; return `Wk ${week}`; }
function row(name, values, classFor = () => '') { const total = values.reduce((a,b)=>a+b,0); return `<tr><td>${name}</td>${values.map((v,i)=>`<td class="${classFor(v,i)}">${typeof v === 'string' ? v : fmt(v)}</td>`).join('')}<td class="total">${fmt(total)}</td></tr>`; }
function renderGrid() { const weeks = result.weeks, segments = state.segments, supplyByPlant = state.plants.map(p => weeks.map(w => w.capacity ? p.capacity * (1 + (p.ramp || 0) * (w.week - 1) / 100) : 0));
  let html = `<table><thead><tr><th>Measure</th>${weeks.map((_,i)=>`<th>${weekLabel(i)}</th>`).join('')}<th>Total</th></tr></thead><tbody>`;
  const group = name => html += `<tr class="group"><td colspan="${weeks.length+2}"><span class="caret">⌄</span>${name}</td></tr>`;
  group('Supply'); state.plants.forEach((p,i) => html += row(`&nbsp;&nbsp;Capacity — ${p.name}`, supplyByPlant[i]));
  html += row('&nbsp;&nbsp;Planned Production', weeks.map(w=>w.production)); html += row('&nbsp;&nbsp;Arrivals', weeks.map(w=>w.arrivals)); html += row('&nbsp;&nbsp;Projected On-Hand', weeks.map(w=>w.inventory), v => v < state.safetyStock ? 'safety' : ''); html += row('&nbsp;&nbsp;Safety Stock', weeks.map(()=>state.safetyStock));
  group('Demand'); segments.forEach((s,i) => html += row(`&nbsp;&nbsp;Gross Demand — ${s.name}`, weeks.map(w=>w.demand[i]))); html += row('&nbsp;&nbsp;Total Demand', weeks.map(w=>w.demand.reduce((a,b)=>a+b,0)));
  group('Allocation'); segments.forEach((s,i) => html += row(`&nbsp;&nbsp;Shipped — ${s.name}`, weeks.map(w=>w.shipments[i]))); html += row('&nbsp;&nbsp;Backlog', weeks.map(w=>w.backlog.reduce((a,b)=>a+b,0)), v=>v ? 'shortage':''); html += row('&nbsp;&nbsp;Lost Sales', weeks.map(w=>w.lost.reduce((a,b)=>a+b,0)), v=>v ? 'shortage':'');
  group('Measures'); html += row('&nbsp;&nbsp;Fill Rate %', weeks.map(w=>w.demand.reduce((a,b)=>a+b,0) ? w.shipments.reduce((a,b)=>a+b,0)/w.demand.reduce((a,b)=>a+b,0)*100 : 100), v=>v>=98?'healthy':'',); html += row('&nbsp;&nbsp;Capacity Utilization %', weeks.map(w=>w.utilization*100));
  $('planningGrid').innerHTML = html + '</tbody></table>';
  $('planningGrid').querySelectorAll('tbody tr:not(.group)').forEach(tr => tr.querySelectorAll('td').forEach((td,i) => { if (tr.textContent.includes('%') && i > 0) td.textContent = `${Number(td.textContent.replace(/,/g,'')) .toFixed(1)}%`; }));
}
function renderAllocation() { const descriptions = policyDescriptions[state.policy]; $('policyTitle').textContent = policyNames[state.policy]; $('policyDescription').textContent = descriptions; const s = result.summary; $('policyStats').innerHTML = `<div><dt>Overall fill rate</dt><dd>${pct(s.fillRate)}</dd></div><div><dt>Captured margin</dt><dd>$${fmt(s.margin)}</dd></div><div><dt>Backlog</dt><dd>${fmt(s.backlog)}</dd></div><div><dt>Reserve</dt><dd>${state.reservePct}%</dd></div>`;
  const rows = result.totals.map((t,i)=>({i,t,fill:t.demand?t.shipped/t.demand:1})).sort((a,b)=>a.fill-b.fill); $('allocationRows').innerHTML = rows.map(({i,t,fill})=>`<tr><td>${state.segments[i].name}</td><td>${pct(fill)}</td><td>$${fmt(t.margin)}</td><td class="${t.lost?'shortage':''}">${fmt(t.lost)}</td><td>${state.segments[i].tier}</td></tr>`).join('');
}
function renderExceptions() { const alerts = [], weeks = result.weeks; weeks.forEach((w,i)=> { if (w.inventory < state.safetyStock) alerts.push({severity:'High', title:`${weekLabel(i)} — Projected on-hand below safety stock (${fmt(w.inventory - state.safetyStock)})`, text:'Projected available inventory is below the configured safety-stock target.', date:weekLabel(i)}); }); state.plants.forEach(p => { if (p.outageStart) alerts.push({severity:'High',title:`Wk ${p.outageStart}–${p.outageEnd} — ${p.name} outage: capacity −100%`,text:'A source outage removes planned capacity from the active supply plan.',date:`Wk ${p.outageStart}`}); }); result.totals.forEach((t,i)=> { const rate = t.demand ? t.shipped/t.demand : 1; if (rate < .9) alerts.push({severity:'Medium',title:`${state.segments[i].name} — fill rate ${pct(rate)} below 90% target`,text:'Segment service is below the configured planning target.',date:'Horizon'}); }); if (!alerts.length) alerts.push({severity:'Low',title:'No material supply exceptions detected',text:'All current simulated measures are within their configured thresholds.',date:'Horizon'});
  $('exceptionCount').textContent = alerts.length; $('exceptionTotal').textContent = `${alerts.length} open`; $('exceptionList').innerHTML = alerts.map(a=>`<div class="exception"><span class="severity ${a.severity.toLowerCase()}">${a.severity}</span><div><strong>${a.title}</strong><p>${a.text}</p></div><time>${a.date}</time></div>`).join('');
}
function renderAssumptions() { const entries = [['Planning horizon', `${state.weeks} weeks`],['Starting inventory', fmt(state.startingInventory)],['Safety stock target', fmt(state.safetyStock)],['Demand multiplier', `${state.demandMultiplier || 100}%`],['Allocation policy', policyNames[state.policy]],['Random seed', state.seed], ...state.plants.map(p=>[p.name, `${fmt(p.capacity)} capacity · ${p.yield}% yield · ${p.leadTime} wk lead`])]; $('assumptionTable').innerHTML = entries.map(([l,v])=>`<div class="assumption"><span class="label">${l}</span><span class="value">${v}</span></div>`).join(''); }
function render() { const run = JSON.parse(JSON.stringify(state)); run.segments.forEach(s => s.baseline *= (state.demandMultiplier || 100) / 100); result = simulate(run); renderCharts(result); renderKpis(); renderGrid(); renderAllocation(); renderExceptions(); renderAssumptions(); $('horizon').textContent = `${state.weeks} weekly buckets · starting Wk 40 2026`; $('statusPolicy').textContent = policyNames[state.policy].replace(' allocation',''); $('statusSeed').textContent = state.seed; $('lastRun').textContent = new Intl.DateTimeFormat(undefined,{hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date()); writeHash(); }
function pathSet(path, value) { let o=state, keys=path.split('.'); keys.slice(0,-1).forEach(k=>o=o[k]); o[keys.at(-1)] = Number(value); }
function preset(name) { state=cloneDefaults(); activePreset=name; if(name==='shock'){state.plants[1].outageStart=8;state.plants[1].outageEnd=11}else if(name==='surge')state.demandMultiplier=145;else if(name==='lead')state.plants.forEach(p=>p.leadTime+=4); $('scenarioName').textContent=`Scenario: ${name === 'shock' ? 'Supply Shock' : name === 'surge' ? 'Demand Surge' : name === 'lead' ? 'Long Lead Times' : 'Balanced'}`; controls(); render(); }
function writeHash(){try{history.replaceState(null,'','#'+btoa(JSON.stringify(state)))}catch{}}
function readHash(){try{if(location.hash){state=Object.assign(state,JSON.parse(atob(location.hash.slice(1))));activePreset='balanced'}}catch{}}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1800)}
document.addEventListener('input',e=>{const id=e.target.id;if(['weeks','inventory','safety','demand','reserve'].includes(id)){const keys={weeks:'weeks',inventory:'startingInventory',safety:'safetyStock',demand:'demandMultiplier',reserve:'reservePct'};state[keys[id]]=Number(e.target.value);$(`${id}Out`).value=e.target.value+(id==='demand'||id==='reserve'?'%':'')}else if(e.target.dataset.path)pathSet(e.target.dataset.path,e.target.value);else if(id==='seed')state.seed=Number(e.target.value);render()});
$('policy').addEventListener('change',e=>{state.policy=e.target.value;render()});document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>preset(b.dataset.preset));$('seedBtn').onclick=()=>{state.seed=Math.floor(Math.random()*1e9);activePreset='balanced';controls();render()};$('pin').onclick=()=>{pinned={...result.summary};toast('Scenario A pinned')};$('runPlan').onclick=()=>{render();toast('Plan run completed')};$('csv').onclick=()=>{const h=['week','demand','arrivals','shipped','inventory','backlog','constraint'];const data=result.weeks.map(w=>[w.week,w.demand.reduce((a,b)=>a+b,0),w.arrivals,w.shipments.reduce((a,b)=>a+b,0),w.inventory,w.backlog.reduce((a,b)=>a+b,0),w.constraint]);const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([[h,...data].map(r=>r.join(',')).join('\n')],{type:'text/csv'}));a.download='supply-model-results.csv';a.click();URL.revokeObjectURL(a.href)};$('share').onclick=async()=>{try{await navigator.clipboard.writeText(location.href);toast('Shareable link copied')}catch{toast('Copy this page URL from your browser')}};
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.tab-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active');if(b.dataset.tab==='allocation') renderCharts(result);});document.querySelectorAll('.accordion-title').forEach(b=>b.onclick=()=>{const body=b.nextElementSibling, open=!body.hidden;body.hidden=open;b.setAttribute('aria-expanded',String(!open));});document.querySelectorAll('.rail-item').forEach(b=>b.onclick=()=>{if(b.dataset.module!=='Supply')toast('Module not included in this mock')});$('paramsOpen').onclick=()=>$('controls').classList.add('open');$('paramsClose').onclick=()=>$('controls').classList.remove('open');$('railToggle').onclick=()=>toast('Supply Planning modules are shown below');readHash();controls();render();
