import { cloneDefaults, simulate } from './model.js';
import { renderCharts } from './charts.js';
let state = cloneDefaults(), result, pinned = null, order = {key:'week', dir:1};
const $ = id => document.getElementById(id), fmt = n => Math.round(n).toLocaleString(), pct = n => `${(n*100).toFixed(1)}%`;
function set(id, val, suffix='') { $(id).value = val; $(`${id}Out`).value = `${val}${suffix}`; }
function controls() {
  set('weeks',state.weeks); set('inventory',state.startingInventory); set('safety',state.safetyStock); set('demand',state.demandMultiplier || 100,'%'); set('reserve',state.reservePct,'%'); $('seed').value=state.seed; $('policy').value=state.policy;
  $('plants').innerHTML=state.plants.map((p,i)=>`<div class="mini"><b>${p.name}</b><label>Weekly capacity <output>${fmt(p.capacity)}</output><input data-path="plants.${i}.capacity" type="range" min="0" max="1500" step="10" value="${p.capacity}"><input data-path="plants.${i}.capacity" type="number" min="0" max="1500" step="10" value="${p.capacity}"></label><label>Yield <output>${p.yield}%</output><input data-path="plants.${i}.yield" type="range" min="50" max="100" value="${p.yield}"><input data-path="plants.${i}.yield" type="number" min="50" max="100" value="${p.yield}"></label><label>Lead time <output>${p.leadTime} wk</output><input data-path="plants.${i}.leadTime" type="range" min="0" max="12" value="${p.leadTime}"><input data-path="plants.${i}.leadTime" type="number" min="0" max="12" value="${p.leadTime}"></label></div>`).join('');
  $('segments').innerHTML=state.segments.map((s,i)=>`<div class="mini"><b>${s.name}</b><small>Tier ${s.tier} · $${s.margin}/unit · ${s.backorder?'backorder':'lost sales'}</small><label>Baseline demand <output>${fmt(s.baseline)}</output><input data-path="segments.${i}.baseline" type="range" min="20" max="800" step="10" value="${s.baseline}"><input data-path="segments.${i}.baseline" type="number" min="20" max="800" step="10" value="${s.baseline}"></label><label>Growth <output>${s.growth}%</output><input data-path="segments.${i}.growth" type="range" min="-2" max="5" step=".1" value="${s.growth}"><input data-path="segments.${i}.growth" type="number" min="-2" max="5" step=".1" value="${s.growth}"></label></div>`).join('');
}
function render() {
  const run = JSON.parse(JSON.stringify(state)); run.segments.forEach(s=>s.baseline*= (state.demandMultiplier||100)/100); result=simulate(run); renderCharts(result); renderKpis(); renderTable(); writeHash();
}
function renderKpis() { const s=result.summary, d=pinned?{fillRate:s.fillRate-pinned.fillRate,shipped:s.shipped-pinned.shipped,margin:s.margin-pinned.margin,inventory:s.inventory-pinned.inventory}:null;
 const cards=[['Overall fill rate',pct(s.fillRate),'fillRate'],['Units shipped',fmt(s.shipped),'shipped'],['Backlog',fmt(s.backlog)],['Lost sales',fmt(s.lost)],['Captured margin','$'+fmt(s.margin),'margin'],['Ending inventory',fmt(s.inventory),'inventory'],['Constrained weeks',s.constrainedWeeks+'/'+state.weeks],['Avg. capacity use',pct(s.utilization)]];
 $('kpis').innerHTML=cards.map(([n,v,k])=>`<div class="kpi"><span>${n}</span><strong>${v}</strong>${d&&k?`<em>${d[k]>=0?'+':''}${k==='fillRate'?pct(d[k]):fmt(d[k])} vs A</em>`:''}</div>`).join('');
 $('compare').hidden=!pinned; if(pinned) $('compare').textContent='Comparing current scenario to pinned Scenario A. Deltas are shown on key KPIs.';
}
function renderTable(){const rows=result.weeks.map(w=>({week:w.week,demand:w.demand.reduce((a,b)=>a+b,0),arrivals:w.arrivals,shipped:w.shipments.reduce((a,b)=>a+b,0),inventory:w.inventory,backlog:w.backlog.reduce((a,b)=>a+b,0),constraint:w.constraint})).sort((a,b)=>typeof a[order.key]==='string'?order.dir*a[order.key].localeCompare(b[order.key]):order.dir*(a[order.key]-b[order.key]));$('weekly').querySelector('tbody').innerHTML=rows.map(r=>`<tr><td>${r.week}</td><td>${fmt(r.demand)}</td><td>${fmt(r.arrivals)}</td><td>${fmt(r.shipped)}</td><td>${fmt(r.inventory)}</td><td>${fmt(r.backlog)}</td><td>${r.constraint}</td></tr>`).join('')}
function pathSet(path,value){let o=state;const keys=path.split('.');keys.slice(0,-1).forEach(k=>o=o[k]);o[keys.at(-1)]=Number(value)}
function preset(name){state=cloneDefaults();if(name==='shock'){state.plants[1].outageStart=8;state.plants[1].outageEnd=11}else if(name==='surge'){state.demandMultiplier=145}else if(name==='lead'){state.plants.forEach(p=>p.leadTime+=4)}controls();render()}
function writeHash(){try{history.replaceState(null,'','#'+btoa(JSON.stringify(state)))}catch{}}
function readHash(){try{if(location.hash) state=Object.assign(state,JSON.parse(atob(location.hash.slice(1))))}catch{}}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1800)}
document.addEventListener('input',e=>{const id=e.target.id;if(['weeks','inventory','safety','demand','reserve'].includes(id)){const keys={weeks:'weeks',inventory:'startingInventory',safety:'safetyStock',demand:'demandMultiplier',reserve:'reservePct'};state[keys[id]]=Number(e.target.value);$(`${id}Out`).value=e.target.value+(id==='demand'||id==='reserve'?'%':'')}else if(e.target.dataset.path)pathSet(e.target.dataset.path,e.target.value);else if(id==='seed')state.seed=Number(e.target.value);render()});
$('policy').addEventListener('change',e=>{state.policy=e.target.value;render()});document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>preset(b.dataset.preset));$('seedBtn').onclick=()=>{state.seed=Math.floor(Math.random()*1e9);controls();render()};$('pin').onclick=()=>{pinned={...result.summary};toast('Scenario A pinned')};$('csv').onclick=()=>{const h=['week','demand','arrivals','shipped','inventory','backlog','constraint'];const data=result.weeks.map(w=>[w.week,w.demand.reduce((a,b)=>a+b,0),w.arrivals,w.shipments.reduce((a,b)=>a+b,0),w.inventory,w.backlog.reduce((a,b)=>a+b,0),w.constraint]);const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([[h,...data].map(r=>r.join(',')).join('\n')],{type:'text/csv'}));a.download='supply-model-results.csv';a.click();URL.revokeObjectURL(a.href)};
$('share').onclick=async()=>{try{await navigator.clipboard.writeText(location.href);toast('Shareable link copied')}catch{toast('Copy this page URL from your browser')}};$('menu').onclick=()=>$('controls').classList.add('open');$('closeMenu').onclick=()=>$('controls').classList.remove('open');document.querySelectorAll('#weekly th').forEach(th=>th.onclick=()=>{order={key:th.dataset.key,dir:order.key===th.dataset.key?-order.dir:1};renderTable()});readHash();controls();render();
