import { cloneDefaults, simulate } from './model.js?v=7dfa636';
import { renderCharts } from './charts.js?v=7dfa636';
const $ = id => document.getElementById(id), fmt = n => Math.round(n).toLocaleString(), day = i => { const d=new Date(Date.UTC(2026,8,28+i*7)); return d.toISOString().slice(0,10); };
let state=cloneDefaults(), result, preset='balanced', stateHistory=[], redo=[], dirty=false, windowStart=0, buckets={graph:1,table:1};
function clone(x){return JSON.parse(JSON.stringify(x))}
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1800)}
function remember(){stateHistory.push(clone(state));if(stateHistory.length>20)stateHistory.shift();redo=[];updateHistory()}
function updateHistory(){$('undo').disabled=!stateHistory.length;$('redo').disabled=!redo.length}
function markDirty(){dirty=true;$('save').disabled=false}
function field(label,value,path,type='number'){return '<label>'+label+'<input type="'+type+'" data-path="'+path+'" value="'+value+'"></label>'}
function controls(){
  ['weeks','inventory','safety','demand','seed','reserve'].forEach(id=>$(id).value=state[{inventory:'startingInventory',safety:'safetyStock',demand:'demandMultiplier'}[id]||id]||100);
  $('policy').value=state.policy;$('preset').value=preset;
  $('plants').innerHTML=state.plants.map((p,i)=>'<div class="mini-field"><b>'+p.name+'</b>'+field('Weekly capacity',p.capacity,'plants.'+i+'.capacity')+field('Yield %',p.yield,'plants.'+i+'.yield')+field('Lead time',p.leadTime,'plants.'+i+'.leadTime')+field('Outage window',p.outageStart||0,'plants.'+i+'.outageStart')+'</div>').join('');
  $('segments').innerHTML=state.segments.map((s,i)=>'<div class="mini-field"><b>'+s.name+'</b>'+field('Baseline',s.baseline,'segments.'+i+'.baseline')+field('Growth %',s.growth,'segments.'+i+'.growth')+field('Priority tier',s.tier,'segments.'+i+'.tier')+field('Margin',s.margin,'segments.'+i+'.margin')+'<label>Backorder <input type="checkbox" data-path="segments.'+i+'.backorder" '+(s.backorder?'checked':'')+'></label></div>').join('');
}
function run(){
  const c=clone(state);c.segments.forEach(s=>s.baseline*=((state.demandMultiplier||100)/100));result=simulate(c);renderCharts(result,showShortfall);renderGrid();renderEngine();
  const end=day(state.weeks-1);['graphFrom','tableFrom'].forEach(id=>$(id).value=day(windowStart));['graphTo','tableTo'].forEach(id=>$(id).value=end);writeHash();
}
function renderEngine(){const ws=result.weeks, safety=ws.filter(w=>w.inventory<state.safetyStock).length, constrained=ws.filter(w=>w.constrained).length,lost=result.totals.filter(t=>t.lost>0).length,served=ws.filter(w=>w.demand.reduce((a,b)=>a+b,0)&&w.shipments.reduce((a,b)=>a+b,0)>=w.demand.reduce((a,b)=>a+b,0)).length;$('highCount').textContent=ws.filter(w=>w.lost.reduce((a,b)=>a+b,0)>0).length;$('safetyCount').textContent=safety;$('servedCount').textContent=served;$('constrainedCount').textContent=constrained;$('lostCount').textContent=lost;$('exceptionList').innerHTML=ws.filter(w=>w.constrained).slice(0,3).map(w=>'<li>Wk '+w.week+': supply constraint</li>').join('')||'<li>No open exceptions</li>'}
function weekValues(i,measure){const w=result.weeks[i];if(measure==='demand')return w.demand;if(measure==='lost')return w.lost;if(measure==='backlog')return w.backlog;if(measure==='fill')return w.demand.map((d,j)=>d?w.shipments[j]/d:1);return w.shipments}
function renderGrid(){
 const agg=$('aggregation').value, measure=$('measure').value, weeks=result.weeks, lead=Math.max(...state.plants.map(p=>p.leadTime||0)), indexes=Array.from({length:weeks.length},(_,i)=>i).filter(i=>i>=windowStart);
 let rows=[];
 if(agg==='plant')rows=state.plants.map((p,j)=>({name:p.name,tier:'—',rule:'Capacity',values:weeks.map(w=>w.capacity? p.capacity*(1+(p.ramp||0)*(w.week-1)/100):0),dem:weeks.map(w=>w.capacity? p.capacity*(1+(p.ramp||0)*(w.week-1)/100):0),ship:weeks.map(w=>w.arrivals),fill:weeks.map(w=>w.capacity? w.arrivals/w.capacity:1)}));
 else if(agg==='total')rows=[{name:'Total plan',tier:'—',rule:'Active policy',values:weeks.map((_,i)=>weekValues(i,measure).reduce((a,b)=>a+b,0)),dem:weeks.map(w=>w.demand.reduce((a,b)=>a+b,0)),ship:weeks.map(w=>w.shipments.reduce((a,b)=>a+b,0)),fill:weeks.map(w=>{const d=w.demand.reduce((a,b)=>a+b,0);return d?w.shipments.reduce((a,b)=>a+b,0)/d:1})}];
 else {const totalCapacity=state.plants.reduce((sum,p)=>sum+p.capacity*p.yield/100,0);rows=state.segments.flatMap((s,j)=>state.plants.map(p=>{const share=(p.capacity*p.yield/100)/totalCapacity;return {name:s.name+' · '+p.name,tier:s.tier,rule:state.policy,values:weeks.map((_,i)=>weekValues(i,measure)[j]*share),dem:weeks.map(w=>w.demand[j]*share),ship:weeks.map(w=>w.shipments[j]*share),fill:weeks.map(w=>w.demand[j]?w.shipments[j]/w.demand[j]:1),index:j}}));}
 const headers=indexes.map(i=>'<th class="'+(i===lead?'boundary':'')+'">'+day(i).slice(5).replace('-', '/')+'/'+day(i).slice(0,4)+'<small>Σ '+fmt(weeks[i].demand.reduce((a,b)=>a+b,0))+'</small></th>').join('');
 const body=rows.map(r=>{const total=r.dem.reduce((a,b)=>a+b,0), shipped=r.ship.reduce((a,b)=>a+b,0), fill=total?Math.min(1,shipped/total):1;const cells=indexes.map(i=>{const v=r.values[i], lost=weeks[i].lost.reduce((a,b)=>a+b,0), editable=measure==='demand'&&r.index!=null;const shown=measure==='fill'?(v*100).toFixed(1)+'%':fmt(v);return '<td data-week="'+i+'" class="'+(i<lead?'frozen ':'')+(i===lead?'boundary ':'')+(measure==='fill'&&v<.9?'bad ':'')+(lost?'lost-dot ':'')+'" '+(editable?'data-edit="'+r.index+':'+i+'"':'')+'>'+shown+'</td>'}).join('');return '<tr><td><input class="check" type="checkbox"></td><td>'+r.name+'</td><td>'+r.tier+'</td><td>'+r.rule+'</td><td>'+fmt(total)+'</td><td>'+fmt(shipped)+'</td><td class="'+(fill<.9?'bad':'')+'">'+(fill*100).toFixed(1)+'%</td>'+cells+'</tr>'}).join('');
 $('planningGrid').innerHTML='<table><thead><tr><th></th><th>Segment</th><th>Tier</th><th>Policy Rule</th><th>Demand Total ↓</th><th>Shipped Total</th><th>Fill %</th>'+headers+'</tr></thead><tbody>'+body+'</tbody></table>';
 document.querySelectorAll('[data-edit]').forEach(td=>td.onclick=()=>{const key=td.dataset.edit,old=td.textContent.replace(/,/g,'');td.innerHTML='<input class="cell-input" type="number" value="'+old+'">';const input=td.firstChild;input.focus();input.select();input.onchange=()=>{remember();state.demandOverrides ||= {};state.demandOverrides[key]=Number(input.value);markDirty();run()};input.onblur=()=>run()});
}
function showShortfall(index,event){const w=result.weeks[index], gap=Math.max(0,w.needs.reduce((a,b)=>a+b,0)-w.shipments.reduce((a,b)=>a+b,0)), pop=$('shortfallPop');pop.hidden=false;pop.style.left=Math.min(event.x,500)+'px';pop.style.top='35px';pop.innerHTML='<strong>Supply Shortfall</strong>Wk '+w.week+' shows '+fmt(gap)+' units less than demand.<br><button id="resolve">Resolve</button>';$('resolve').onclick=()=>{remember();state.policy='hybrid';state.reservePct=50;markDirty();controls();run();pop.hidden=true;toast('Suggested Hybrid policy applied')}}
function presetRun(name){remember();state=cloneDefaults();preset=name;if(name==='shock'){state.plants[1].outageStart=8;state.plants[1].outageEnd=11}else if(name==='surge')state.demandMultiplier=145;else if(name==='lead')state.plants.forEach(p=>p.leadTime+=4);controls();run()}
function pathSet(path,val,checked){let o=state,ks=path.split('.');ks.slice(0,-1).forEach(k=>o=o[k]);o[ks.at(-1)]=checked===undefined?Number(val):checked}
function writeHash(){try{window.history.replaceState(null,'','#'+btoa(JSON.stringify(state)))}catch{}}
function readHash(){try{if(location.hash)state=Object.assign(state,JSON.parse(atob(location.hash.slice(1))))}catch{}}
document.addEventListener('change',e=>{if(e.target.dataset.path){remember();pathSet(e.target.dataset.path,e.target.value,e.target.type==='checkbox'?e.target.checked:undefined);markDirty();run()}else if(['weeks','inventory','safety','demand','seed','reserve'].includes(e.target.id)){remember();state[{inventory:'startingInventory',safety:'safetyStock',demand:'demandMultiplier'}[e.target.id]||e.target.id]=Number(e.target.value);markDirty();run()}});
$('exceptionList').hidden=true;
['aggregation','measure'].forEach(id=>$(id).onchange=renderGrid);$('policy').onchange=e=>{remember();state.policy=e.target.value;markDirty();run()};$('preset').onchange=e=>presetRun(e.target.value);$('save').onclick=()=>{toast('Scenario A pinned for comparison');dirty=false;$('save').disabled=true};$('refresh').onclick=()=>presetRun(preset);$('upload').onclick=()=>toast('Upload is not included in this mock');$('help').onclick=()=>toast('Use filters to adjust the constrained plan');$('share').onclick=async()=>{try{await navigator.clipboard.writeText(location.href);toast('Shareable link copied')}catch{toast('Copy this page URL from your browser')}};$('csv').onclick=()=>{const rows=['week,demand,arrivals,shipped,inventory,backlog'];result.weeks.forEach(w=>rows.push([w.week,w.demand.reduce((a,b)=>a+b,0),w.arrivals,w.shipments.reduce((a,b)=>a+b,0),w.inventory,w.backlog.reduce((a,b)=>a+b,0)].join(',')));const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([rows.join('\n')],{type:'text/csv'}));a.download='supplyplan.csv';a.click()};$('undo').onclick=()=>{redo.push(clone(state));state=stateHistory.pop();controls();run();updateHistory()};$('redo').onclick=()=>{stateHistory.push(clone(state));state=redo.pop();controls();run();updateHistory()};$('exceptionsToggle').onclick=()=>{$('exceptionList').hidden=!$('exceptionList').hidden};$('sidebarToggle').onclick=()=>$('sidebar').classList.toggle('open');$('closeSidebar').onclick=()=>$('sidebar').classList.remove('open');$('recenter').onclick=()=>{windowStart=0;run()};document.querySelectorAll('.segment button').forEach(b=>b.onclick=()=>{b.parentElement.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');buckets[b.parentElement.dataset.bucket]=Number(b.dataset.value);});['graphFrom','tableFrom'].forEach(id=>$(id).onchange=e=>{windowStart=Math.max(0,Math.round((new Date(e.target.value+'T00:00:00Z')-new Date('2026-09-28T00:00:00Z'))/604800000));run()});readHash();controls();document.querySelectorAll('.segment button[data-value="1"]').forEach(b=>b.classList.add('active'));run();
